### ISSUE TITLE
Error in step 'fillChains'

### ISSUE THREAD

**Issue by DiegoSafian** [hillerlab/make_lastz_chains#15]
Hi ,
I have been facing a problem with make_chains.py. When I align Target genome with query genome A (contigs 186, genome lenght 600Mb) worked perfectly fine. But thenwhen I want to align a query B (contigs 1500, 700 mb) against the same target, I always found an error in step fillChains. Species A and B are closely related. I was wondering what is wrong. I am attaching the .log file.
Thanks in advance,
Diego
[make_chains.log](https://github.com/hillerlab/make_lastz_chains/files/11125133/make_chains.log)

**Comment by DiegoSafian** [comment]
I think I am missing  RepeatFiller.py

**Comment by MichaelHiller** [comment]
Maybe you have an old git clone. We added RepeatFiller as git submodule (https://github.com/hillerlab/GenomeAlignmentTools) 6 months ago. 
Pls do a clean git pull and try again.

**Comment by kirilenkobm** [comment]
If it's still relevant, please try the updated pipeline version (2.0.0) which will be released within next 24 hours.
Please create a new issue if you experience any troubles.
