### ISSUE TITLE
NOTE: Process `execute_jobs (64)` terminated with an error exit status (2) -- Execution is retried (1)

### ISSUE THREAD

**Issue by gunjanpandey** [hillerlab/make_lastz_chains#18]
Could you please help with?

```
N E X T F L O W  ~  version 21.10.1
Launching `XXXXX/TEMP_run.lastz/lastz_chickenNB/script.nf` [maniac_yonath] - revision: 20fae9dc0e
[-        ] process > execute_jobs -

executor >  local (17)
[37/e70339] process > execute_jobs (4) [  0%] 0 of 190

executor >  local (49)
[b9/89be59] process > execute_jobs (19) [  0%] 0 of 225

executor >  local (50)
[2a/0acf5d] process > execute_jobs (46) [  0%] 1 of 226, failed: 1, retries: 1
[2a/0acf5d] NOTE: Process `execute_jobs (46)` terminated with an error exit status (2) -- Execution is retried (1)

executor >  local (51)
[3c/cbb0c0] process > execute_jobs (51) [  0%] 2 of 227, failed: 2, retries: 2
[d2/aff088] NOTE: Process `execute_jobs (64)` terminated with an error exit status (2) -- Execution is retried (1)

```

**Comment by BoBo2021jenny** [comment]
Hi
The error is ：
N E X T F L O W  ~  version 22.10.0
Launching `/data/zhangbo/software/make_lastz_chains/Tele2Ppup/TEMP_run.lastz/lastz_PpupTele/script.nf` [soggy_wescoff] DSL1 - revision: ad8af5e7ff
/tmp/nxf-11857650355126268811
/software/miniconda3/envs/NF/lib/python3.8/site-packages/py_nf/py_nf.py:404: UserWarning: Nextflow pipeline lastz_PpupTele failed! Execute function returns 1.
  warnings.warn(msg)
Could you please help me solve the problem ?

**Comment by kirilenkobm** [comment]
Hi @BoBo2021jenny 

To solve the DSL issue please downgrade nextflow below `22.12.0`.
I did not have enough capacity to solve the issue in this pipeline, but it it is planned.

**Comment by kirilenkobm** [comment]
Hi all.
Today or tomorrow I will release and updated pipeline version where the nextflow problems are sorted out.
If you still experience any troubles pls create a new issue.
