### ISSUE TITLE
The issue with the temporary file generation path.

### ISSUE THREAD

**Issue by hcsun1** [hillerlab/make_lastz_chains#20]
Hello, 

when running make_chains.py on two 700MB genomes, the temporary files were stored in /dev/mapper/cl-root, which caused the storage of /dev/mapper/cl-root to be filled up and eventually resulted in the termination of make_chains.py. Could you please advise on how to modify the temporary file generation path for make_chains.py? Thank you very much for your help.

##Centos7

**Comment by kirilenkobm** [comment]
Hello!
Sorry for the long period of silence (I don't work in Michael's lab anymore, and had a lot of other things to do).
Thank you for submitting the issue, I will have a look at the temporary files placement.
