### ISSUE TITLE
RepeatFiller

### ISSUE THREAD

**Issue by Sandhyash** [hillerlab/make_lastz_chains#22]
HgAutomate::run("TEMP_run.lastz"...) called at make_lastz_chains/doLastzChains/HgRemoteScript.pm line 117

HgRemoteScript::execute(HgRemoteScript=HASH(0x557801b9a758)) called at make_lastz_chains/doLastzChains/doLastzChain.pl line 370

main::doPartition() called at make_lastz_chains/doLastzChains/HgStepManager.pm line 169

HgStepManager::execute(HgStepManager=HASH(0x557801b45280)) called at make_lastz_chains/doLastzChains/doLastzChain.pl line 877

**Comment by kirilenkobm** [comment]
Hi @Sandhyash 

pls try the updated pipeline version and let me know if the issue still persists.
