### ISSUE TITLE
nextflow

### ISSUE THREAD

**Issue by BoBo2021jenny** [hillerlab/make_lastz_chains#23]
Hi
I met a error about nextflow. I used nextflow version 20 in ubuntu. Could you help me?
N E X T F L O W  ~  version 20.10.0
Launching `/software/make_lastz_chains/Tele2Ppup/TEMP_run.lastz/lastz_PpupTele/script.nf` [romantic_albattani] - revision: d48f32974e
/tmp/nxf-13131159217981153035
/software/miniconda3/envs/NF/lib/python3.8/site-packages/py_nf/py_nf.py:404: UserWarning: Nextflow pipeline lastz_PpupTele failed! Execute function returns 1.

**Comment by kirilenkobm** [comment]
Hi! If it's still relevant, a new, completely rearranged version of the pipeline will be released today or tomorrow. Probably, it will be no longer an issue.
