### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by ebioman** [hillerlab/make_lastz_chains#24]
I think there might be some missing requirements

- faToTwoBit
- twoBitToFa
- gensub2
- Nextflow: version beyond 22.10.x are not anymore supporting DSL1

**Comment by kirilenkobm** [comment]
Hi! Thank you for your comment. 
Today or tomorrow I will release a completely rearranged version of the pipeline, where the nextflow issue is fixed, and dependencies are revised.
