### ISSUE TITLE
Runs fail at doChainRun step,

### ISSUE THREAD

**Issue by ohdongha** [hillerlab/make_lastz_chains#3]
I was running alignments for a pair of Drosophila genomes and human vs. mouse.  Both runs failed at the `doChainRun` step. 

Commands used:
```
# for Drosophila pairs
make_chains.py Dme Dsi GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna GCF_016746395.2_Prin_Dsim_3.1_genomic.fna --executor_queuesize 16 --project_dir 220722_LastZ_chain_DmeDsi_1stAttempt > 220722_lsz_DmeDsi_1stAttempt.log 2>&1 
# for human vs. mouse
make_chains.py h38 m39 GCF_000001405.40_GRCh38.p14_genomic.fna GCF_000001635.27_GRCm39_genomic.fna --executor_queuesize 32 --project_dir 220722_LastZ_chain_h38m39_1stAttempt > 220722_lsz_h38m39_1stAttempt.log 2>&1 #2 
```
Attached are log files for both runs.  
[220722_lsz_h38m39_1stAttempt.log](https://github.com/hillerlab/make_lastz_chains/files/9182240/220722_lsz_h38m39_1stAttempt.log)
[220722_lsz_DmeDsi_1stAttempt.log](https://github.com/hillerlab/make_lastz_chains/files/9182241/220722_lsz_DmeDsi_1stAttempt.log)

The complaints were that a certain chrom couldn't be found in `.chrom.sizes` files:
```
# for Drosophila pairs 
ERROR: file /export/home/TMP/771717715.1.unified/tmp.oHfdzTtayi/NW_001845981.psl was not bundled as the chrom could not be found in ./220722_LastZ_chain_DmeDsi_1stAttempt/Dme.chrom.sizes
# for human vs. mouse
ERROR: file /export/home/TMP/771851000.1.unified/tmp.apDCgOGofk/NC_000015.psl was not bundled as the chrom could not be found in ./220722_LastZ_chain_h38m39_1stAttempt/h38.chrom.sizes
```

But I can see both of them (with `.*` suffixes) in `*.chrom.sizes`. 
```
$ grep "NW_001845981" 220722_LastZ_chain_DmeDsi_1stAttempt/Dme.chrom.sizes
NW_001845981.1  1643
$ grep "NC_000015" 220722_LastZ_chain_h38m39_1stAttempt/h38.chrom.sizes
NC_000015.10    101991189
```

Will having `.*` suffixes in sequence names be a problem?  Please help. 
Thanks!

**Comment by ohdongha** [comment]
> Will having .* suffixes in sequence names be a problem? 

I modified all sequence IDs to remove `.` (e.g. "NC_052520.2" -> "NC_052520__2"), and the Drosophila alignment went through and generated a compressed `chain` file!   I started the human-mouse alignment again, also with modified sequence IDs.

If the sequence ID with `.` was indeed the cause of the crash, it would be nice to have a caution in the document (or perhaps I missed it...).  Thanks!

**Comment by MichaelHiller** [comment]
Perfect. 
This is a known quirk and this is why we always remove the .{number} from scaffold names. 

@kirilenkobm Can you pls add a note in bold red font to the HOWTO that people need to strip the .1? Alternatively, your workflow could do this automatically.

**Comment by ohdongha** [comment]
Since I was able to get results by modifying the sequence headers, I will close this issue.
