### ISSUE TITLE
Stats for chain + psl (or axt) intermediate files?

### ISSUE THREAD

**Issue by ohdongha** [hillerlab/make_lastz_chains#4]
Hello again, 
I am now exploring the first `chain` output I obtained from a successful run :)  

I am curious how we can get basic stats for the alignments:
1. What portions of genomes were covered by the primary alignment (`.psl` or `.axt`) and the chains (`.chain`)?
2. Were some portions of genomes covered multiple times (if so, how much and how many times)?
3. What are the length distributions of all primary and chained alignments?
4. Distributions of distances (e.g. substitutions per site or any other measure of similarities) among alignments?    

I can extract and process the headers of the `chain` file to answer some of the above questions, but I wonder if there are already tools to do so.  

Plus, especially for item 4, we may need the `.psl` (or `.axt`?) alignment since `.chain` appears to have dropped the information on the similarity scores of alignments.  Is there a way to retrieve a concatenated `.psl` alignment file?   

Here are the files and folders in the output directory after the run:
```
$ ls -1tr 220725_LastZ_chain_DmeDsi_2ndAttempt
Dme.2bit
Dme.chrom.sizes
Dsi.2bit
Dsi.chrom.sizes
DEF
make_chains_py_params.json
master_script.sh
TEMP_psl
TEMP_run.lastz
TEMP_pslParts
TEMP_run.cat
TEMP_run.fillChain
Dme.Dsi.allfilled.chain.gz
TEMP_axtChain
cleanUp.csh
```
Thanks!

**Comment by ohdongha** [comment]
Hello again, 
I realize that we can convert the `chain` to `asn` alignment file and then there are a bunch of internal tools that can find stats and visualize.   Plus, I found that the `psl` (or `axt`) files, etc. are not needed for our purpose.  

So I would say this issue was resolved itself :)  Thanks again and I'll come back if I meet some other issues (human vs. mouse is almost done, and I am looking forwards to browsing it).

**Comment by AswinSSoman** [comment]
Can you please suggest a way to convert the `chain` file to an `asn` alignment file?

Regards,
Aswin

**Comment by MichaelHiller** [comment]
To my knowledge (but I haven't ever used asn as a format), there is no tool for that. 
UCSC provides chainToAxt which is human readable and 
chainToPsl (does not display the alignment directly), 
but there is no chainToAsn or so. 

Sorry
