### ISSUE TITLE
Cant find the final chain file

### ISSUE THREAD

**Issue by sangeet2019** [hillerlab/make_lastz_chains#5]
I am trying to run this tool to get genome alignment chains (very useful, many thanks). It runs without any complains, and I can see in the log file that the program is completed. But, unfortunately I dont see the final chain file as output in the output directory I specify. Am I missing anything here ?

Here is what I am doing, 

/Tools/make_lastz_chains/make_chains.py target_id query_id target.fa query.fa --project_dir Lastz_run1

It runs for a day and completed without any issue. I just dont see the output file. Any thoughts what may be wrong ?

**Comment by kirilenkobm** [comment]
Hi @sangeet2019 

Could you pls share the output of the command:
```
ls Lastz_run1
```

There must be a file called "target_id.query_id.allfilled.chain.gz" which is the final output.
Pls let me know whether it is present or not.

**Comment by sangeet2019** [comment]
-rw-rw-r--.  1 sangeet sangeet 299M Aug  6 19:39 chicken.2bit
-rw-rw-r--.  1 sangeet sangeet  13K Aug  6 19:39 chicken.chrom.sizes
-rw-rw-r--.  1 sangeet sangeet 1.2K Aug  6 19:39 DEF
-rw-rw-r--.  1 sangeet sangeet  23K Aug  7 08:27 make_chains.log
-rw-rw-r--.  1 sangeet sangeet  530 Aug  6 19:39 make_chains_py_params.json
-rwxrwxr-x.  1 sangeet sangeet  747 Aug  6 19:39 master_script.sh
-rw-rw-r--.  1 sangeet sangeet 250M Aug  6 19:39 partridge.2bit
-rw-rw-r--.  1 sangeet sangeet 213K Aug  6 19:39 partridge.chrom.sizes
drwxrwxr-x. 10 sangeet sangeet 4.0K Aug  6 19:40 TEMP_psl
drwxrwxr-x.  5 sangeet sangeet 4.0K Aug  6 19:40 TEMP_run.lastz

So, it has all the temporary files etc, I dont see the final chain file

**Comment by MichaelHiller** [comment]
Hi Sangeet, 

looks like the lastz run did not finish. 
Do you have a log file? What does it show at the end? 

Are there lastz jobs that errored or timed out on your cluster (or crashed with out of memory, which is rarely the case). 
This is the most likely explanation. 

(I would also just start it again to see if the issue is reproducible). 

Pls send us the logs and we will have a look.

**Comment by MichaelHiller** [comment]
Hi Sangeet, 
Bogdan added a small code addition to output an error message if the final output file (chain) is not found. 
Would be great if you could test it. 
Pls let us know if there are still issues.

**Comment by sangeet2019** [comment]
Thanks Michael for working on this. I have ran it multiple times. No issues with time out or memory crash. All runs to completion. Just the final chain file is not generated.

I will test the new code.

**Comment by sangeet2019** [comment]
[make_chain.log.txt](https://github.com/hillerlab/make_lastz_chains/files/9462633/make_chain.log.txt)

**Comment by MichaelHiller** [comment]
This is strange. Your 208 genome-wide all vs all lastz jobs finish fine, but then nothing is executed anymore. 
@kirilenkobm There must be some command at the end of the lastz step that crashes, causing the whole pipeline to stop and not advance to the next step. Which commands come after the lastz commands?

**Comment by kirilenkobm** [comment]
Let's execute some individual lastz command and see. First of all, we need to export all necessary directories
Can /scratch/slamichh/Partridge/Alignment_with_chicken/Chicken_vs_Partridge_RMasked/master_script.sh and execute all four "export ... " commands from this file. 
Then cd to /scratch/slamichh/Partridge/Alignment_with_chicken/Chicken_vs_Partridge_RMasked/TEMP_run.lastz/ and open jobList.
Pls execute some command with -v flag and copypaste the output here.
This will output the exact lastz output: pls also try this, but replace the output (4th argument) with /dev/stdout

**Comment by kirilenkobm** [comment]
@MichaelHiller 

Lastz command is something like lastz "target.2bit/$chrom[$start,$end][multiple]"  "query.2bit/$chrom[$start,$end][multiple]" H=2000 Y=9400 L=3000 K=2400 --traceback=800.0M --format=axt+
Then in the same job
axtToPsl /dev/stdin target.chrom.sizes query.chrom.sizes stdout

**Comment by MichaelHiller** [comment]
Right, I read from the logs that all lastz jobs run fine. 
But I don't see the '************ HgStepManager: executing step ....
Therefore I wondered if there is another command after the lastz jobs but before starting the next step (e.g. getting runtime stats?)

**Comment by MichaelHiller** [comment]
Sangeet, can you pls check if 
$buildDir/TEMP_run.lastz/lastz.done
that file (lastz.done) exists? This is literally the last command that is executed in the lastz step. 

If that file exists, pls try to restart doLastzChain.pl at the next 'cat' step by adding '-continue cat' as a parameter.
Pls go to your project dir where you have the 'DEF' file and run:
cat $PROJECT_DIR/master_script.sh | grep export
# then execute these exports to define to the variable and add the tools to $PATH 
doLastzChain.pl DEF -continue cat

**Comment by sangeet2019** [comment]
Thanks Michael. Your suggestions worked !! :)

**Comment by MichaelHiller** [comment]
Glad to hear that. Pls close this issue if no other problems remain. 
Any idea why the pipeline stopped after the lastz step and did not automatically continue? 
Thx

**Comment by sangeet2019** [comment]
Thanks. Yeah, no idea why it kept stopping exactly at the same point every time.
