### ISSUE TITLE
lastz options to obtain the "best path" alignments?

### ISSUE THREAD

**Issue by ohdongha** [hillerlab/make_lastz_chains#6]
Hello again, 
With your help, I was able to get chain alignments for human-mouse, human-zebrafish, etc.  

I used the NCBI soft-masked genomes, and it seems like the repeat-masking was indeed not enough.   I can see blocks of many dense and short diagonal lines, i.e. alignments from repeats that escaped the masking.  I am re-doing the alignments using UCSC soft-masked (RepeatMasker + TRF?) genomes, plus genomes masked with RepeatModeler + RepeatMasker (as @MichaelHiller suggested).

We are interested in identifying the "best path" alignments, where the two genomes could be more or less 1:1 covered as continuously as possible.  (This could become 1:many or many:many if either of both genomes has whole genome duplications, but I would like to think about it later...). 

So here are a few questions:
- Reading the `lastz` manual, it seems like there are options (e.g. `--gfextend --chain --gapped` [in Fig 2f](http://www.bx.psu.edu/miller_lab/dist/README.lastz-1.02.00/README.lastz-1.02.00a.html#ex_stages) ) and steps (chaining, interpolation by `--inner=`, etc.) that could help longer and "cleaner" alignments.  I wonder whether these steps and options were already applied.  For example, is `FILL_CHAIN=1` essentially performing interpolation?
- What does CLEANCHAIN=1 do?  Will it try to reduce the number of e.g. non-reciprocal chains?   
- Other than the more extensive repeat-masking, would there be any other suggestions to obtain the "best" or better paths?  Would modifying the H, Y, L, and K parameters be helpful in any way?  

Thanks again!
Dong-Ha

**Comment by MichaelHiller** [comment]
Hi Dong-Ha, 

Not sure if UCSC does its own repeatMasking these days (but pls ask). 

To your questions: 
1) We haven't tried these lastz parameters. Let us know how they work. RepeatFiller (FILL_CHAIN=1)  would unmask regions that do not align but are bounded by aligning blocks, which is something I believe lastz does not do. 
2) chainCleaner improves alignment specificity. More here; https://pubmed.ncbi.nlm.nih.gov/28108446/
3) Modifying lastz parameters would change alignment specificity/sensitivity and runtimes, but would not tell you which genomic loci have no duplications and are "best path". I guess one way to get best-path alignments could be extracting long chains for which the reference and query locus is not covered by other high-scoring chains that could represent real duplications. UCSC nets is an approach to select "A" single best alignment for each reference locus, but there can still be duplications. 

Hope that helps

**Comment by ohdongha** [comment]
Thanks a lot, @MichaelHiller.  Here are a few more questions: 

Among the `lastz` options I mentioned, I realized that `--gfextend --gapped` are ON by default.  Also the `BLASTZ_H=2000` may be equivalent to `--inner=2000` so this functionality seems to be on as well.  The only option that is not default is `--chain` but I am not sure whether `make_lastz_chains` has a step similar to this option in a different form.

Q1: For a test, will it be possible to add `--chain` option to the base `lastz` command incorporated in the `make_lastz_chains` workflow? If yes, how can we do so - is there a particular script that we could try to modify (by adding `--chain`)?   

And the RepeatFiller (FILL_CHAIN=1) might be the reason why the final output is named, e.g. "hg38.mm39.*allfilled*.chain.gz" (for human and mouse).  On the other hand, [the pairwise alignment from UCSC](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/vsMm39/) has a `lastz` chain file named "hg38.mm39.all.chain.gz."  

Q2: Do you think if we suppress the `RepeatFiller`, we will get something similar to (or better than, because of the `chainCleaner`) the UCSC alignment ("hg38.mm39.all.chain.gz")?  I am asking because the UCSC chain alignment appears to have much fewer long alignments (e.g. >20Kb) that are derived from repeats, than the one created by `make_lastz_chains`.   

Q3: In the default `DEF` file, I'm also seeing "FILL_UNMASK=1" option.  Could you briefly explain what this does?   

I will also look into UCSC nets.  Thanks again!

**Comment by MichaelHiller** [comment]
Hi, 

For Q1, pls try to find the actual lastz command and add --chain there. 
Correct, if you enable RepeatFiller, you get an allfilled.chain.gz file. (allfilled to indicate that RepeatFiller was run).

Q2
If you disable RepeatFiller and ChainCleaner and use UCSC parameters, you will get something very similar to UCSC. Not sure why you want to do that. 

Q3. 
This option indicates whether the RepeatFiller will unmask (everything upper case) the unaligning seqs for which it runs another round of lastz alignments. If you set this to 0, you may not find repeat-overlapping alignments. 

Michael

**Comment by ohdongha** [comment]
Thanks a lot, Michael, for your input here and also during the email communication.  I think we have all answers so I will close this issue. 
Thanks again!
Dong-Ha
