### ISSUE TITLE
the position is different from its annotation file.

### ISSUE THREAD

**Issue by summyyy** [hillerlab/make_lastz_chains#71]
Hi, authors!
The pipeline is very good! I ran it successfully. But why the transcript's  start and end position of reference species in the final chain file is different from  its annotation file (gtf file)? 
This figure generated by visualizing the loss_summ_data.tsv ,which generated by TOGA pipeline. We can see the transcript ID is XM_038500000.1, and the chain iD is 84.
![微信图片_20241127202723](https://github.com/user-attachments/assets/fc2fac3c-d4c9-4243-a405-0ef48a6681bb)
Then i looked for XM_038500000.1 from the chain file that generated by this pipeline (but i only chose one chormosome of reference species with fasta format and the query species' whole genome as input file. so, I also want to know whether one chormosome of reference species vs query species' whole genome is effective? the whole genome of reference species to make chain file is mandatory? ) . The start position is 72940933 and the end is 73027286.
![微信图片_20241127202720](https://github.com/user-attachments/assets/982b47b0-9a55-4052-9580-633b62788827)
At the same time I opened the annotation file (gtf file) for the reference species. But the start position is 31660621 and the end is also far less than 73027268.
![微信图片_20241127202706(1)](https://github.com/user-attachments/assets/de1b1895-ad3a-4a3e-838b-dab6c7034ee1)
Could you tell me that's why? It is important to me.
Thank you.

**Comment by MichaelHiller** [comment]
This should go into the TOGA github, but I'll answer it here. 
Chains and gene annotations are two different things. 
The start/end of chain 84 just tell you where the chain of co-linear local alis starts and ends. This chain seems to cover this XM_0385 transcript and this transcript will have its own coordinates inside this chain region.

**Comment by summyyy** [comment]
Thanks for your reply!   
Emmmmmm, I still don't understand. The transcript ID XM_038500000.1 corredponds to the gene "FAM133B". However, I imported the start and end position of the chain fille into NCBI, and the result did not contain _FAM133B_. 
Because I want to know  the exact location of the XM_038500000.1 in the query species, I locate it in the chain file by "84" in the first figure. Or maybe I have a wrong understanding for this 84? Could you tell me  what the "84" in the first figure means? What is its function and how to use it correctly ? In my opinion, the "84" represents the corresponding chain id in the chain file. 
I'm sorry that some questions related to TOGA were discusseded here. If necessary, I will copy these questions and answers to TOGA github.
Best wishes!

**Comment by MichaelHiller** [comment]
To locate where TOGA predicts the ortholog of XM_038 to be in your query assembly, pls look into the query_annotation.bed file. This is THE annotation. 

The chains are just the genome alignment. 
84 is the chain ID.

**Comment by summyyy** [comment]
Thank you.
But in the TOGA pipeline , there is no query_annotation.bed as input file. I don't know how to screen the ortholog of XM_038500000.1 in the query_annotation.bed. The XM_038500000.1 is just the reference species' transcript id. And I want to know what message does the "84" in the first figure send? I thought it was meant to direct me to the line with chain id 84 to find relevant information.

**Comment by MichaelHiller** [comment]
OK, you want the position of a transcript in the reference (not the query). 
Then pls get this from the toga.transcripts.bed which is the input

**Comment by summyyy** [comment]
Thank you very much!
